src/com/xiangrui/lmp/business/admin/coupon/vo/Coupon.java
package com.xiangrui.lmp.business.admin.coupon.vo;

import com.xiangrui.lmp.business.base.BaseCoupon;

/**
 * 优惠券
 * <p>
 * @author <b>hsjing</b>
 * </p>
 * <p>
 * 2015-6-4 下午3:16:55
 * </p>
 */
public class Coupon extends BaseCoupon
{

    private static final long serialVersionUID = 1L;

    /**
     * 是否过期
     */
    private int guoq;

    /**
     * 开始日期
     */
    private int denominationStrat;

    /**
     * 结束日期
     */
    private int denominationEnd;

    public int getGuoq()
    {
        return guoq;
    }

    public void setGuoq(int guoq)
    {
        this.guoq = guoq;
    }

    public int getDenominationStrat()
    {
        return denominationStrat;
    }

    public void setDenominationStrat(int denominationStrat)
    {
        this.denominationStrat = denominationStrat;
    }

    public int getDenominationEnd()
    {
        return denominationEnd;
    }

    public void setDenominationEnd(int denominationEnd)
    {
        this.denominationEnd = denominationEnd;
    }

}

src/com/xiangrui/lmp/business/admin/coupon/vo/CouponUsed.java
package com.xiangrui.lmp.business.admin.coupon.vo;

import com.xiangrui.lmp.business.base.BaseCouponUsed;

public class CouponUsed extends BaseCouponUsed
{
	private int actual_coupon_id;

	public int getActual_coupon_id()
	{
		return actual_coupon_id;
	}

	public void setActual_coupon_id(int actual_coupon_id)
	{
		this.actual_coupon_id = actual_coupon_id;
	}
}

src/com/xiangrui/lmp/business/admin/coupon/vo/UserCoupon.java
package com.xiangrui.lmp.business.admin.coupon.vo;

import com.xiangrui.lmp.business.base.BaseUserCoupon;

public class UserCoupon extends BaseUserCoupon
{
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String userName;
	private int haveUsedCount;
	private int avalidCount;
	private int actual_coupon_id;
	private String account;

	public String getAccount()
	{
		return account;
	}

	public void setAccount(String account)
	{
		this.account = account;
	}

	public int getActual_coupon_id()
	{
		return actual_coupon_id;
	}

	public void setActual_coupon_id(int actual_coupon_id)
	{
		this.actual_coupon_id = actual_coupon_id;
	}

	public int getAvalidCount()
	{
		return avalidCount;
	}

	public void setAvalidCount(int avalidCount)
	{
		this.avalidCount = avalidCount;
	}

	public String getUserName()
	{
		return userName;
	}

	public void setUserName(String userName)
	{
		this.userName = userName;
	}

	public int getHaveUsedCount()
	{
		return haveUsedCount;
	}

	public void setHaveUsedCount(int haveUsedCount)
	{
		this.haveUsedCount = haveUsedCount;
	}

}

src/com/xiangrui/lmp/business/homepage/vo/AdvertVo.java
package com.xiangrui.lmp.business.homepage.vo;


/**
 * ClassName:AdvertVo. <br/>
 * description [翔锐物流首页轮播广告]
 * Date:     2015年4月23日19:55:06<br/>
 * @author   ltp
 * @version  1.0
 * @since    JDK 1.7
 */
public class AdvertVo {

	/**.
	 * 广告名称
	 */
	private String advertName;
	
	/**.
	 * 广告图片路径
	 */
	private String advertImage;
	
	/**.
	 * 广告图片标题
	 */
	private String advertTitle;
	
	/**.
	 * 广告图片简介
	 */
	private String advertIntroduction;
	
	/**.
	 * 广告链接
	 */
	private String advertLink;

    /**.
     * 链接打开方式
     */
	private String openType;
	
	/**.
	 * 显示顺序
	 */
	private String advertOrder;
	
	public AdvertVo() {
		super();
	}

	public String getAdvertName() {
		return advertName;
	}

	public void setAdvertName(String advertName) {
		this.advertName = advertName;
	}

	public String getAdvertImage() {
		return advertImage;
	}

	public void setAdvertImage(String advertImage) {
		this.advertImage = advertImage;
	}

	public String getAdvertTitle() {
		return advertTitle;
	}

	public void setAdvertTitle(String advertTitle) {
		this.advertTitle = advertTitle;
	}

	public String getAdvertIntroduction() {
		return advertIntroduction;
	}

	public void setAdvertIntroduction(String advertIntroduction) {
		this.advertIntroduction = advertIntroduction;
	}

	public String getAdvertLink() {
		return advertLink;
	}

	public void setAdvertLink(String advertLink) {
		this.advertLink = advertLink;
	}

	public String getOpenType() {
		return openType;
	}

	public void setOpenType(String openType) {
		this.openType = openType;
	}

	public String getAdvertOrder() {
		return advertOrder;
	}

	public void setAdvertOrder(String advertOrder) {
		this.advertOrder = advertOrder;
	}

}

src/com/xiangrui/lmp/business/homepage/vo/ExpressEnum.java
package com.xiangrui.lmp.business.homepage.vo;
/**
 * 快件包裹 0：不是 1：是（原来的字段意思）
 * 渠道：渠道：0默认；1A渠道；2B渠道；3C渠道；4D渠道；5E渠道 （现在的字段意思）
 */
//private int express_package;
public enum ExpressEnum {
	F_(0,"F渠道"),
	A_(1,"A渠道"),
	B_(2,"B渠道");
    
    private int id;
    private String msg;

    private ExpressEnum(int id, String msg) {
        this.msg = msg;
        this.id = id;
    }

    public String getMsg() {
        return msg;
    }

    public int getId() {
        return id;
    }
}

src/com/xiangrui/lmp/business/homepage/vo/FrontAccountLog.java
package com.xiangrui.lmp.business.homepage.vo;

import com.xiangrui.lmp.business.base.BaseAccountLog;

public class FrontAccountLog extends BaseAccountLog
{

    /**
     * 
     */
    private static final long serialVersionUID = 1L;
}

src/com/xiangrui/lmp/business/homepage/vo/FrontCity.java
package com.xiangrui.lmp.business.homepage.vo;

import com.xiangrui.lmp.business.base.BaseCity;

public class FrontCity extends BaseCity
{

}

src/com/xiangrui/lmp/business/homepage/vo/FrontCouponUsed.java
package com.xiangrui.lmp.business.homepage.vo;

import java.io.Serializable;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;

public class FrontCouponUsed implements Serializable
{
    /**
     * 时间格式化
     */
    private static final SimpleDateFormat simpleDateFormat = new SimpleDateFormat(
            "yyyy-MM-dd HH:mm:ss");

    /**
     * 
     */
    private static final long serialVersionUID = 1L;

    /**
     * 优惠券id
     */
    private int coupon_id;

    /**
     * 编号
     */
    private String coupon_code;

    /**
     * 用户id
     */
    private String user_id;

    /**
     * 来源
     */
    private String resource;

    /**
     * 面额
     */
    private float denomination;

    /**
     * 数量
     */
    private int quantity;

    /**
     * 使用日期
     */
    private Timestamp use_date;

    /**
     * 订单号
     */
    private int order_code;

    /**
     * json显示时间用
     */
    private String use_date_string;
    
    private String logistics_code;

    public String getLogistics_code()
	{
		return logistics_code;
	}

	public void setLogistics_code(String logistics_code)
	{
		this.logistics_code = logistics_code;
	}

	public int getCoupon_id()
    {
        return coupon_id;
    }

    public void setCoupon_id(int coupon_id)
    {
        this.coupon_id = coupon_id;
    }

    public String getCoupon_code()
    {
        return coupon_code;
    }

    public void setCoupon_code(String coupon_code)
    {
        this.coupon_code = coupon_code;
    }

    public String getUser_id()
    {
        return user_id;
    }

    public void setUser_id(String user_id)
    {
        this.user_id = user_id;
    }

    public String getResource()
    {
        return resource;
    }

    public void setResource(String resource)
    {
        this.resource = resource;
    }

    public float getDenomination()
    {
        return denomination;
    }

    public void setDenomination(float denomination)
    {
        this.denomination = denomination;
    }

    public int getQuantity()
    {
        return quantity;
    }

    public void setQuantity(int quantity)
    {
        this.quantity = quantity;
    }

    public Timestamp getUse_date()
    {
        return use_date;
    }

    public String getUse_date_toStr()
    {
        if (null != use_date)
        {
            return use_date.toString().trim().replace(".0", "");
        } else
        {
            return "";
        }
    }

    public void setUse_date(Timestamp use_date)
    {
        this.use_date = use_date;
        // json 显示时间用
        this.use_date_string = simpleDateFormat.format(use_date).toString();
    }

    public int getOrder_code()
    {
        return order_code;
    }

    public void setOrder_code(int order_code)
    {
        this.order_code = order_code;
    }

    public String getUse_date_string()
    {
        return use_date_string;
    }

}

src/com/xiangrui/lmp/business/homepage/vo/FrontGoodsType.java
package com.xiangrui.lmp.business.homepage.vo;

import com.xiangrui.lmp.business.base.BaseGoodsType;

public class FrontGoodsType extends BaseGoodsType
{


    private static final long serialVersionUID = 1L;
    /**
     * 申报类别排序用的
     */
    private String idFramework;
    
    public String getIdFramework()
    {
        return idFramework;
    }
    public void setIdFramework(String idFramework)
    {
        this.idFramework = idFramework;
    }

    
}

src/com/xiangrui/lmp/business/homepage/vo/FrontIdCardInfor.java
package com.xiangrui.lmp.business.homepage.vo;

import java.io.Serializable;

public class FrontIdCardInfor implements Serializable{

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private String area;	// 身份证地址
	private String sex;
	private String birthday;
	public String getArea() {
		return area;
	}
	public void setArea(String area) {
		this.area = area;
	}
	public String getSex() {
		return sex;
	}
	public void setSex(String sex) {
		this.sex = sex;
	}
	public String getBirthday() {
		return birthday;
	}
	public void setBirthday(String birthday) {
		this.birthday = birthday;
	}
	
	
}

src/com/xiangrui/lmp/business/homepage/vo/FrontIdcard.java
package com.xiangrui.lmp.business.homepage.vo;

import com.xiangrui.lmp.business.base.BaseIdcard;

public class FrontIdcard extends BaseIdcard{

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	public FrontIdcard(){
	    
	}

	public FrontIdcard(FrontIdcardResult ir){
		this.setArea(ir.getIdCardInfor().getArea());
		this.setBirthday(ir.getIdCardInfor().getBirthday());
		this.setIdcard(ir.getIdcard());
		this.setRealname(ir.getRealname());
		this.setSex(ir.getIdCardInfor().getSex());
	}
}

src/com/xiangrui/lmp/business/homepage/vo/FrontIdcardResult.java
package com.xiangrui.lmp.business.homepage.vo;

import java.io.Serializable;

public class FrontIdcardResult implements Serializable{
	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private String idcard;	// 身份证号
	private String realname;	// 人名
	private boolean isok;	// 是否匹配成功
	private FrontIdCardInfor IdCardInfor;
	
	public String getIdcard() {
		return idcard;
	}
	public void setIdcard(String idcard) {
		this.idcard = idcard;
	}
	public String getRealname() {
		return realname;
	}
	public void setRealname(String realname) {
		this.realname = realname;
	}
	public boolean isIsok() {
		return isok;
	}
	public void setIsok(boolean isok) {
		this.isok = isok;
	}
	public FrontIdCardInfor getIdCardInfor() {
		return IdCardInfor;
	}
	public void setIdCardInfor(FrontIdCardInfor idCardInfor) {
		IdCardInfor = idCardInfor;
	}
	
}

src/com/xiangrui/lmp/business/homepage/vo/FrontOverSeaAddress.java
package com.xiangrui.lmp.business.homepage.vo;

import com.xiangrui.lmp.business.base.BaseOverseasAddress;

public class FrontOverSeaAddress extends BaseOverseasAddress
{

}

src/com/xiangrui/lmp/business/homepage/vo/FrontPkgAttachService.java
package com.xiangrui.lmp.business.homepage.vo;

import com.xiangrui.lmp.business.base.BasePkgAttachService;

public class FrontPkgAttachService extends BasePkgAttachService
{

    /**
     * 
     */
    private static final long serialVersionUID = 1L;

    /**
     * 物流跟踪号
     */
    private String logistics_code;

    /**
     * 增值服务名称
     */
    private String service_name;

    /**
     * 增值服务价格
     */

    private float service_price;

    public String getLogistics_code()
    {
        return logistics_code;
    }

    public void setLogistics_code(String logistics_code)
    {
        this.logistics_code = logistics_code;
    }

    public String getService_name()
    {
        return service_name;
    }

    public void setService_name(String service_name)
    {
        this.service_name = service_name;
    }

    public float getService_price()
    {
        return service_price;
    }

    public void setService_price(float service_price)
    {
        this.service_price = service_price;
    }
}

src/com/xiangrui/lmp/business/homepage/vo/FrontReceiveAddress.java
package com.xiangrui.lmp.business.homepage.vo;

import com.xiangrui.lmp.business.base.BaseUserAddress;

public class FrontReceiveAddress extends BaseUserAddress
{

    private static final long serialVersionUID = 1L;

    private String addressStr;

    public String getAddressStr()
    {
        return addressStr;
    }

    public void setAddressStr(String addressStr)
    {
        this.addressStr = addressStr;
    }
}

src/com/xiangrui/lmp/business/homepage/vo/FrontSender.java
package com.xiangrui.lmp.business.homepage.vo;

import com.xiangrui.lmp.business.base.BaseSender;

public class FrontSender extends BaseSender{

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

}

src/com/xiangrui/lmp/business/homepage/vo/FrontUserAddress.java
package com.xiangrui.lmp.business.homepage.vo;

import com.xiangrui.lmp.business.base.BaseUserAddress;

public class FrontUserAddress extends BaseUserAddress
{



    /**
     * 
     */
    private static final long serialVersionUID = 1L;

    private String addressStr;

    public String getAddressStr()
    {
        return addressStr;
    }

    public void setAddressStr(String addressStr)
    {
        this.addressStr = addressStr;
    }

}

src/com/xiangrui/lmp/business/homepage/vo/FrontUserCoupon.java
package com.xiangrui.lmp.business.homepage.vo;

import java.io.Serializable;
import java.sql.Timestamp;
import java.text.SimpleDateFormat;

public class FrontUserCoupon implements Serializable
{
    /**
     * 时间格式化
     */
    private static final SimpleDateFormat simpleDateFormat = new SimpleDateFormat(
            "yyyy-MM-dd HH:mm:ss");

    /**
     * 
     */
    private static final long serialVersionUID = 1L;

    /**
     * 优惠券id
     */
    private int coupon_id;

    /**
     * 编号
     */
    private String coupon_code;

    /**
     * 用户id
     */
    private int user_id;

    /**
     * 来源
     */
    private String resource;

    /**
     * 面额
     */
    private float denomination;

    /**
     * 用户可以一次性获得的数量
     */
    private int quantity;

    /**
     * 是否可以叠加使用，1：是；2：否
     */
    private int is_repeat_use;

    /**
     * 有效日期
     */
    private Timestamp valid_date;

    /**
     * 状态，1：未使用，2：已使用
     */
    private int status;

    /**
     * 使用日期
     */
    private Timestamp use_date;

    /**
     * 订单号
     */
    private int order_code;

    /**
     * json显示时间用
     */
    private String valid_date_string;

    /**
     * json显示时间用
     */
    private String use_date_string;

    public int getCoupon_id()
    {
        return coupon_id;
    }

    public void setCoupon_id(int coupon_id)
    {
        this.coupon_id = coupon_id;
    }

    public String getCoupon_code()
    {
        return coupon_code;
    }

    public void setCoupon_code(String coupon_code)
    {
        this.coupon_code = coupon_code;
    }

    public int getUser_id()
    {
        return user_id;
    }

    public void setUser_id(int user_id)
    {
        this.user_id = user_id;
    }

    public float getDenomination()
    {
        return denomination;
    }

    public void setDenomination(float denomination)
    {
        this.denomination = denomination;
    }

    public int getQuantity()
    {
        return quantity;
    }

    public void setQuantity(int quantity)
    {
        this.quantity = quantity;
    }

    public int getIs_repeat_use()
    {
        return is_repeat_use;
    }

    public void setIs_repeat_use(int is_repeat_use)
    {
        this.is_repeat_use = is_repeat_use;
    }

    public Timestamp getValid_date()
    {
        return valid_date;
    }

    public String getValid_date_toStr()
    {
        if (null != valid_date)
        {
            return valid_date.toString().trim().replace(".0", "");
        } else
        {
            return "";
        }
    }

    public void setValid_date(Timestamp valid_date)
    {
        this.valid_date = valid_date;
        // json 显示时间用
        this.valid_date_string = simpleDateFormat.format(valid_date).toString();
    }

    public int getStatus()
    {
        return status;
    }

    public void setStatus(int status)
    {
        this.status = status;
    }

    public Timestamp getUse_date()
    {
        return use_date;
    }

    public String getUse_date_toStr()
    {
        if (null != use_date)
        {
            return use_date.toString().trim().replace(".0", "");
        } else
        {
            return "";
        }
    }

    public void setUse_date(Timestamp use_date)
    {
        this.use_date = use_date;
        // json 显示时间用
        this.use_date_string = simpleDateFormat.format(use_date).toString();
    }

    public String getValid_date_string()
    {
        return valid_date_string;
    }

    public String getUse_date_string()
    {
        return use_date_string;
    }

    public String getResource()
    {
        return resource;
    }

    public void setResource(String resource)
    {
        this.resource = resource;
    }

    public int getOrder_code()
    {
        return order_code;
    }

    public void setOrder_code(int order_code)
    {
        this.order_code = order_code;
    }

}

WebContent/WEB-INF/page/homepage/frt/coupon.jsp
<%@ page language="java" contentType="text/html; charset=UTF-8" pageEncoding="UTF-8"%>
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>优惠券</title>
    <script src="${resource_path}/js/jquery.1.11.3.js"></script>
    <script src="${resource_path}/js/jquery.js"></script>
    <script src="${resource_path}/js/bootstrap.min.js"></script>
    <script src="${resource_path}/js/slideUp.js"></script>
    <script src="${resource_path}/js/layer.min.js"></script>
    <script type="text/javascript" src="${resource_path}/js/common.js"></script>
    <script type="text/javascript" src="${resource_path}/js/TransportNewList.js"></script> 
    <link rel="stylesheet" href="${resource_path}/css/iconfont.css">
    <link rel="stylesheet" href="${resource_path}/css/bootstrap.css">
    <link rel="stylesheet" href="${resource_path}/css/global.css">
    <link rel="stylesheet" href="${resource_path}/css/indexs.css">
    <link rel="stylesheet" type="text/css" href="${resource_path}/css/sycommon.css">
    <link rel="stylesheet" type="text/css" href="${resource_path}/css/sycount.css">
    <link href="${resource_path}/css/common.css" rel="stylesheet" type="text/css">
	<style type="text/css">
	    .couponli{width:33%; float:left; overflow:hidden;}
	</style>
</head>
<body class="bg-f1">
<!--头部开始-->
<div class="top">
    <div class="wrap1200">
        <ul class="right floatR">
            <li><a href="#">返回首页</a></li>
            <li><a href="#">资费说明</a></li>
            <li><a href="#">禁运物品</a></li>
            <li><a href="#">用户指南</a></li>
            <li><a href="#"><i class="icon iconfont icon-qq"></i>客服中心</a></li>
        </ul>
        <p class="left floatL">HI,<a href="#" class="col_orange">tong@qq.com</a><a href="#">[退出]</a> </p>
    </div>
</div>
<div class="header">
    <div class="wrap1200">
        <div class="right floatR">
            <input type="text" placeholder="请输入运单号查询">
            <button><i class="icon iconfont icon-iconfontsousuo"></i></button>
        </div>
        <div class="left floatL">
            <a href="#"><img src="${resource_path}/img/logo.jpg"></a>
            <h3><img src="${resource_path}/img/logo-titile.jpg"></h3>
        </div>
    </div>
</div>
<!--头部结束-->

<!--中间内容开始-->
<div class="main">
    <!--左侧导航栏开始-->
    <div class="left floatL">
        <ul class="sidebar">
            <li ><a href="#"><i class="icon iconfont icon-shouye-shouye"></i>个人中心首页</a> </li>
            <li><a href="#"><i class="icon iconfont icon-tijikongjian"></i>我的包裹<small>${pkgCount}</small></a> </li>
            <li><a href="#"><i class="icon iconfont icon--guoji"></i>海外仓库地址</a> </li>
            <li><a href="#"><i class="icon iconfont icon-dingwei"></i>收货地址</a> </li>
            <li><a href="#"><i class="icon-money"></i>资金记录</a> </li>
            <li><a href="#"><i class="icon iconfont icon-shezhi"></i>账户设置</a> </li>
            <li class="active"><a href="#"><i class="icon iconfont icon-yhq"></i>优惠券<small>${countAvailable}</small></a> </li>
            <!--<li><a href="${mainServer}/account/recommand"><i class="icon iconfont icon-ren"></i>推荐有礼</a> </li>-->
        </ul>
    </div>
    <!--左侧导航栏结束-->

    <!--右侧内容开始-->
    <div class="right">
    	<div class="column mt25 p20">
    		<div class="record">
	          <div class="hr mg18 lastline"></div>			  
			  <div class="size14">优惠券说明：</div> 
				<li class="border-top-none">
	                  <ol>
	                      <li class="span10 size14">1.只有单个包裹进行支付时才能使用优惠券，批量支付不支持使用优惠券</li>
	                      <li class="span10 size14">2.一个包裹只能使用一张优惠券</li>
						  <li class="span10 size14">3.到期后的优惠券将会无效且无法使用</li>
						  <li class="span10 size14">4.优惠券最终解释权归跨境物流所有</li>
					  </ol>
	              </li> 
			  <br><br><br><br><br><br>
	          <a name="Coupon"></a>
	          <p class="size14" style="margin-left:0;"><strong class="pd10">优惠券：</strong>共 <span class="totalCount">${countAll}</span> 张</p>
	               <div class="opt" >
	                   <ul class="function pull-left couponul" style="width:400px;">
	                       <li class="current couponli" id="one">
	                       <a style="cursor:pointer;">可使用优惠券</a>
	                       <span class="count" style="float: left; position: absolute;margin:6px 0 0 -21px;">${countAvailable}</span>
	                       </li>
	                       <li class="couponli" id="two"><a style="cursor:pointer;">已使用优惠券</a></li>
	                       <li class="couponli" id="three"><a style="cursor:pointer;">已过期优惠券</a></li>
	                   </ul>
	               </div>
	               
	               <div id="avliable">
	               <ul class="list01 radius3" id="recordlist">
	                  <c:forEach var="userCoupon"  items="${avliableCouponList}">
	                   	<div style="color:##bbbbbb; width:280px; height:180px; border:1px dashed #9CC; float:left; margin:5px 20px 20px 2px;"> 
						<div style="font-size:16px; background-color:#bbbbbb; color:#FFF; text-align:center; padding-top:5px; padding-bottom:5px">${userCoupon.coupon_name}</div>
						<div style="padding-left:5px;">
							优惠券代码：${userCoupon.coupon_code}<br /><br />
							优惠券金额：<b style="font-size:16px; color:#F00"><fmt:formatNumber value="${userCoupon.denomination}" type="currency" pattern="$#,###.00"/></b><br />
							数量：${userCoupon.avalidCount}<br /><br />
							有效期至：${userCoupon.valid_date_toStr}<br />
						</div>
	                    </div>
	                 </c:forEach>
	               </ul>
	               </div>
	               
	               <div id="used" style="display: none">
	                   <ul class="list01 radius3" id="recordlist">
	                  <c:forEach var="couponUsed"  items="${usedCouponList}">
	                  	<div style="color:##bbbbbb; width:280px; height:180px; border:1px dashed #9CC; float:left; margin:5px 20px 20px 2px;">     
						<div style="font-size:16px; background-color:#bbbbbb; color:#FFF; text-align:center; padding-top:5px; padding-bottom:5px">${couponUsed.coupon_name}</div>
						<div style="padding-left:5px;">
							优惠券代码：${couponUsed.coupon_code}<br /><br />
							优惠券金额：<b style="font-size:16px; color:#F00"><fmt:formatNumber value="${couponUsed.denomination}" type="currency" pattern="$#,###.00"/></b><br />
							使用数量：${couponUsed.quantity}<br />
							使用运单号：${couponUsed.order_code}<br />
							使用日期：${couponUsed.use_date}<br />
						</div>
						</div>
	                 </c:forEach>
	               </ul> 
	               </div>
	               
	               <div id="expired" style="display: none">
	               <ul class="list01 radius3" id="recordlist">
	                  <c:forEach var="userCoupon"  items="${expiredCouponList}">
	                	<div style="color:##bbbbbb; width:280px; height:180px; border:1px dashed #9CC; float:left; margin:5px 20px 20px 2px;">   
						<div style="font-size:16px; background-color:#bbbbbb; color:#FFF; text-align:center; padding-top:5px; padding-bottom:5px">${userCoupon.coupon_name}</div>
	 					<div style="padding-left:5px;">
							优惠券代码：${userCoupon.coupon_code}<br /><br />
							优惠券金额：<b style="font-size:16px; color:#F00"><fmt:formatNumber value="${userCoupon.denomination}" type="currency" pattern="$#,###.00"/></b><br /><br />
							优惠券数量：${userCoupon.quantity}<br />
							有效期至：${userCoupon.valid_date_toStr}<br />
						</div>
						</div>
	                 </c:forEach>
	               </ul>
	               </div>                              
	          </div>
    	</div>
    </div>
</div>
<script type="text/javascript">
    $(function () {
        // 优惠券
        $(".couponli").click(function () {
            
            $("ul.couponul>li").removeClass("current");
            $(this).addClass("current");
            var url = "${mainServer}/account/coupon";
            var id =(this).id;
            if(id=="one"){
                $("#avliable").show();
                $("#used").hide();
                $("#expired").hide();
            }else if(id=="two"){
                $("#avliable").hide();
                $("#used").show();
                $("#expired").hide();
            }else{
                $("#avliable").hide();
                $("#used").hide();
                $("#expired").show();
            }           
        });
        

        
        //格式化金额
    function fmoney(s, n) {
            n = n > 0 && n <= 20 ? n : 2;
            s = parseFloat((s + "").replace(/[^\d\.-]/g, "")).toFixed(n) + "";
            var l = s.split(".")[0].split("").reverse();
            var r = s.split(".")[1];
            var t = "";
            for ( var i = 0; i < l.length; i++) {
                t += l[i] + ((i + 1) % 3 == 0 && (i + 1) != l.length ? "," : "");
            }
            return t.split("").reverse().join("") + "." + r;
        }
    });
</script>
<script type="text/javascript" src="${resource_path}/js/ZeroClipboard.js"></script>
<script type="text/javascript">
$(function(){
    $(".left-nav").hover(function () {
        $(this).css("background","url(${resource_path}/img/is5.png) no-repeat");
    }, function () {
        $(this).css("background","url(${resource_path}/img/is6.png) no-repeat");
        });
    
    $("#charge").click(function () {
        var url = "${mainServer}/member/frontUserStatus";
        $.ajax({
            url:url,
            type:'post',
            async:false,
            dataType:'json',
            success:function(data){
                // 账户正常
                if(data.result =="1"){
                    var rechargeOffHeight = ($(window).height() - 570) / 2;
                    $.layer({
                        title :'充值',
                        type: 2,
                        fix: false,
                        shadeClose: true,
                        shade: [0.5, '#ccc', true],
                        border: [1, 0.3, '#666', true],
                        offset: [rechargeOffHeight + 'px', ''],
                        area: ['950px', '570px'],
                        iframe: { src: '${mainServer}/member/rechargeInit'}
                    });
                }
                else{
                   alert(data.message);
                }
            }
        });
    });
});
//包裹状态
function showTransportStatus(status){
	
	window.location.href="${mainServer}/transport?status="+status;
}
//所有状态的包裹
function showAllTransport(){
	window.location.href="${mainServer}/transport";
}
//包裹支付状态
function showTransportPayStatus(payStatus){

	window.location.href="${mainServer}/transport?payStatus="+payStatus;
}
</script>
</body>
</html>